### ISSUE TITLE
Suggestion to add Labels for specific resources for issue tracking

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/SqlServerDsc#1222]
Adding a Label for SQLServerSetup as an example would allow better instant visibility and allow better reporting on which resources get the most issues raised against them

**Comment by johlju** [comment]
Not sure about this one. One one hand it would help with removing the actual resource name from the issue title and PR title. On the other hand that would make it more clear where the issue is more visible and tags are not. It would also be a lot of work re-tagging all issues, and some issue should be tagged with more than one resource tag. 
It would be easier if users could tag issues them self, but now it's only me (collaborators) that have the ability to tag issues.

The resource issue statistics, could it be solved by searching for the resource name? For that to me accurate, then closed issue also need to be tagged.

**Comment by johlju** [comment]
If there is more interest for this, I'm open to this. 🙂
