### ISSUE TITLE
Question - Is it a necessary to publish release with the Test folder in PSGallery

### ISSUE THREAD

**Issue by luigilink** [PowerShell/SqlServerDsc#135]
Can we exclude Test folder from the master release, like they do with SharePointDSC ?

**Comment by johlju** [comment]
I think this one need and answer from @kwirkykat or @mbreakey3.

**Comment by kwirkykat** [comment]
@luigilink @johlju I can exclude the tests if the file structure of this repo is changed to match that of SharePointDsc/OfficeOnlineServerDsc where only the module in the Modules folder is actually published.

**Comment by mbreakey3** [comment]
What's the reason for wanting to exclude them from the published release?

**Comment by luigilink** [comment]
Because Tests are never used when your build a MOF or by the target server, aren't they.
It's an open discussion, because I saw this on SharePointDSC, and I thought it was a good idea. Also final user (like I was on the beginning of DSC, I admit :)) just use the resources and examples.

**Comment by johlju** [comment]
@kwirkykat If that is the file structure for a HQRM then we should change it to be closer to HQRM (every small step counts 😄 ). 

We don't have all the tests in place yet for all the resources in this module. Moving stuff around might break things without a way to verify it works? But if we are confident that we can move all necessary files to a new `/Modules/xSQLServer` folder without breaking anything then I'm all for it.

_Regarding test in release or not._
One reason to keep the tests in the release is that users can do change on the code and test it locally, those not interested in using GitHub or contributing (or doesn't know about either possibility). 
But if we should add the tests to the releases in the future then that should be part of the guideline for a HRQM, and since it is not (right now) I think we should keep the modules looking the same.

**Comment by mbreakey3** [comment]
I agree that we should leave them in for now, as our top priority is getting the resources up to High Quality standards

**Comment by luigilink** [comment]
Totally agree with you @mbreakey3, we have to focus on high quality standards.
Go back on this discussion when xSQLServer will be ready to become SQLServerDSC.

**Comment by randomnote1** [comment]
I really like the idea of not shipping the `Tests` folder with the module. Does this look correct for updating the folder structure? Should there be a `Localization` directory under `DSCResources` to store the localization directories?

- .gitHub
- .vscode
- Modules
  - SqlServerDsc
    - DSCResources
      - _\<All DSC Resources\>_
      - CommonResourceHelper.psm1
    - Examples
    - en-US
    - sv-SE
    - SqlServerDsc.psd1
    - SqlServerDscHelper.psm1
- Tests
- .MetaTestOptIn.json
- .codecov.yml
- .gitignore
- .markdownlint.json
- .CHANGELOG.md
- .CODE_OF_CONDUCT.md
- .CONTRIBUTING.md
- .LICENSE
- .README.md
- .appveyor.yml

**Comment by johlju** [comment]
Please see https://github.com/PowerShell/ComputerManagementDsc for the folder structure. Each resource should have there own localization folders (like today).
The helper modules folders should go under a new Modules folder in the root of SqlServerDsc folder, and should have a separate folder underneath. Example: https://github.com/PowerShell/ComputerManagementDsc/blob/dev/Modules/ComputerManagementDsc/Modules/ComputerManagementDsc.ResourceHelper/ComputerManagementDsc.ResourceHelper.psm1.

Although I like the idea of not publishing the Tests folder and we could use auto-documentation,  this must align with the test framework, where the two different folder structures have different testing models, the Default Shared Model (current) and the "Harness"-model (proposed moving to), and those models doesn't have the same features in the test framework. See issue https://github.com/PowerShell/DscResource.Tests/issues/225 on trying to join these two.
There are two things that must work when this change is done - integration test must still be run in order, and container testing need to work  (this is to speed up tests, that I haven't sent in a PR for yet).
