### ISSUE TITLE
SqlScript: assistance with Get, Test, and Set T-SQL Scripts

### ISSUE THREAD

**Issue by ynauls** [PowerShell/SqlServerDsc#547]
I am new to DSC and I am going through the growing pains and looking for assistance with the following.

I am having difficulties writing the Get T-SQL script, i get the following below.  

_The PowerShell DSC resource  returned results that are not valid from Get-TargetResource. The Username key is not a valid property in the corresponding DSC resource schema file. The results from Get-TargetResource must be in a Hashtable format. The keys in the Hashtable must be the same as the properties in the corresponding DSC resource schema file._

I am looking for an example of the Get, Test, and Set scripts to ensure compliance with the return types.

**Comment by johlju** [comment]
@ynauls Thanks for submitting this issue. Could you possibly post the configuration and scripts you are using? Please remove/replace any sensitive information.

I just posted an example script here; 
https://gist.github.com/johlju/a452c145a0f13b4c60cff4ef47b7e22e
This script does work, but not actually sure `Get-DscConfiguration` works with this example.

Does it give you this error during Test/Set?
Do you have the verbose log that you can post as well?

**Comment by ynauls** [comment]
Thank you @johlju,  my script is as simple as yours for now.  You are correct, the error i got is the same error i get with yours.  the error is on >Get-DscConfiguration is that an expected error for the current version?

**Comment by johlju** [comment]
I keep this open until we added and integration test for the SqlScript resource.

**Comment by johlju** [comment]
@ynauls Sorry for this taking so long to respond to. The problem you had was that you need to return the result in the 'Result` property. That is the only allowed property for returning data, you are not allowed to add any other properties since that does not match the [schema of the resource](https://github.com/PowerShell/SqlServerDsc/blob/dev/DSCResources/MSFT_SqlScript/MSFT_SqlScript.schema.mof).

Easiest is to return the result as either XML och JSON and parse the string in the `Result` property if more advanced logic need to be done on the result returned from `Get-DscConfiguration`.

I sent in a PR with an integration tests that shows this: 
Config: https://github.com/PowerShell/SqlServerDsc/pull/1027/files#diff-7f1eb6108c0df7446080cb681a410470
Integration tests (from line 118): https://github.com/PowerShell/SqlServerDsc/pull/1027/files#diff-1c5d8872862d472d54c87722744f1079R118

**Comment by johlju** [comment]
Let's update one of the examples to show this as well.

**Comment by johlju** [comment]
Added a example in PR #1027. When that PR is merged, this issue will auto-close. @ynauls if there are any outstanding questions, then please reopen this issue. Thanks for helping make the resource better! 😄
