### ISSUE TITLE
SqlServerDscHelper: Localization should no need to use Verbose on Write-Verbose

### ISSUE THREAD

**Issue by johlju** [PowerShell/SqlServerDsc#641]
**Details of the scenario you tried and the problem that is occurring:**
Helper module should use the same method of localization as HQRM resources.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by johlju** [comment]
I will continue work on this when I merged the localization for xSQLServerSetup.

**Comment by johlju** [comment]
I need a bit of help. If someone could come up with an idea I would appreciate it. 

I have an issue with this change (PR #642). It seems $VerbosePreference is not uphold in the helper functions. For example calling `Connect-SQL` gets no verbose message even if `Start-DscConfiguration` is started with `-Verbose` parameter. The resource is writing verbose message, but not the helper functions.

Only solution I found so far is to call the helper functions using `-Verbose:$VerbosePreference`.
Or stick -Verbose behind every `Write-Verbose` in the helper functions.
Or continue using the New-VerboseMessage for the helper functions, but sending in the localized message instead.

I was hoping $VerbosePreference would roll down into the helper functions as well. But it apparently it don't do that (probably because it's another module). 😄 

Previously when  `New-VerboseMessage` was used it worked because it force writing verbose messages by using `-Verbose`. This is the row from `New-VerboseMessage`.
```
Write-Verbose -Message ((Get-Date -format yyyy-MM-dd_HH-mm-ss) + ": $Message") -Verbose
```

Now instead of using `New-VerboseMessage` it is changed to, for example, the following.

```
Write-Verbose -Message ($script:localizedData.ConnectedToDatabaseEngineInstance -f $databaseEngineInstance)
```

I was hoping we didn't have to use New-VerboseMessage. So if there is a simple solution to this, please let me know.

**Comment by PlagueHO** [comment]
Hi @johlju - I've run into this problem as well: The VerbosePreference does not seem to be passed between modules in different scopes. This article covers some stuff on it (but I don't think it's the whole story):
https://powershell.org/2014/01/13/getting-your-script-module-functions-to-inherit-preference-variables-from-the-caller/

The VerbosePreference in the common module uses the VerbosePreference in the Global scope, regardless of what is passed in from the calling code, whereas the calling code uses the local VerbosePreference variable - which doesn't get passed across scopes it seems (or that is my understanding).

I managed to replicate the problem in xCertificate (in fact I noticed that xCertReq exhibits the same problems as you're seeing). I've raised an issue in xCertificate as well: https://github.com/PowerShell/xCertificate/issues/70

Note: xCert accidentally fixes this in some cases by building a splat from the PSBoundParameters object and passing that through to the "common" function which causes the VerbosePreference to be copied through. This is not an ideal solution and requires extra code.

I've tried experimenting with loading the common modules into the Global scope and this makes no difference.

The smallest thing I could come up with was this:
```powershell
$verboseSplat = @{ Verbose = ($PSBoundParameters['Verbose'] -eq $true) }
$caObject = Find-CertificateAuthority @verboseSplat
```
So for xSQLServer it would look like this:
```powershell
$verboseSplat = @{ Verbose = ($PSBoundParameters['Verbose'] -eq $true) }
New-VerboseMessage -Message "Connected to SQL $connectSql" @verboseSplat
```

But as noted, that seems like a crazy workaround to me.

Another way I found that works is to set the Global VerbosePreference like this:

```powershell
        $verbosePreferenceBackup = $Global:VerbosePreference
        $global:VerbosePreference = $VerbosePreference
        New-VerboseMessage -Message "Connected to SQL $connectSql"
        $global:VerbosePreference = $verbosePreferenceBackup
```

But this to my mind is an absolutely terrible idea as well (much worse that the previous idea).

There must be a better way. Perhaps one of the DSC/PowerShell team have some ideas on this because I'm out of ideas :cry:

**Comment by johlju** [comment]
@PlagueHO Thanks for answering on this one! Appreciate it! 😄 

Currently I see two solutions. Which is actually less code than your suggestions above. 

1. Adding parameter `-Verbose:$VerbosePreference` to each call to a helper function in the `*-TargetResource` functions.
```
$databaseServer = Connect-SQL `
                      -SQLServer $sqlHostName `
                      -SQLInstanceName $InstanceName `
                      -Verbose:$VerbosePreference
```

2. Adding `-Verbose` to each call to the cmdlet `Write-Verbose`, in each helper function.
```
Write-Verbose `
    -Message ($script:localizedData.ConnectedToDatabaseEngineInstance -f $databaseEngineInstance) `
    -Verbose
```
Both 1 and 2 writes verbose messages when calling `Start-DscConfiguration` with `-Verbose` parameter, for example `Start-DscConfiguration -Path . -Wait -Verbose`. Also, both these solution correctly does not write any verbose messages if leaving out `-Verbose` in the call, for example `Start-DscConfiguration -Path . -Wait`. I wasn't expecting that, I expected number 2 to write verbose messages since we forcing it write with `-Verbose` on the `Write-Verbose` cmdlet. But somehow those are ignored when `Start-DscConfiguration` is not called with `-Verbose` parameter.

So with this i'm in favor on number 2. Number 2 would simplify for contributors. Not having to think of adding `-Verbose:$VerbosePreference` to the helper function calls in `*-TargetResource`. But at the same time that will make the helper function always write verbose messages even if the user don't want it. But then again, as mentions above, it does seem to from `*-TargetResource` functions, which is the only place they will be used. 

Of course, if `$VerbosePreference` was actually automatically passed as I was hoping, then that would be the best solution.

**Comment by johlju** [comment]
@mbreakey3, @kwirkykat or @TravisEz13 if you have time, could you look at this issue we are having with Write-Verbose in helper functions, and see if you have a better solution? Thanks.

**Comment by PlagueHO** [comment]
Hi @johlju - those are definitely better options - and I am surprised about number 2 working as well. I don't understand why it does though. I'd love to get a better understanding of why. I'd definitely go with number 2 as well. This would definitely be the easiest to resolve (as noted, I have some repos with this problem as well).

**Comment by johlju** [comment]
@PlagueHO Yes, and if there is a better solution, it is easiest to revert number 2 if needed.

**Comment by johlju** [comment]
I have merged the PR using the option 2 mentioned above. I keep this open a while longer if a better solution is suggested. In that case I will send in a new PR changing the code.

**Comment by kwirkykat** [comment]
@johlju @PlagueHO I'm not sure if there's a better option here. I've posted the question to the DSC team. I'll let you know if they have any tips.

**Comment by PlagueHO** [comment]
Thank you @kwirkykat :+1:
