### ISSUE TITLE
Example references bad resource names

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/SqlServerDsc#904]
https://github.com/mgreenegit/SqlServerDsc/blob/dev/Examples/SQL-ClusterDB.ps1

xSQLServerFailoverClusterSetup is not a valid resource name

**Comment by johlju** [comment]
The examples in the root of the example folder contain a lot of issues. I'm working on replacing them in issue #462. In that issue my thought was to split them up between xFailoverCluster and xSQLServer repo as examples in a markdown file, trying to link to examples in each resource example folder. Eventually, I want to see these as configurations in DscConfigurations repository.
But step one is remove the obsolete examples from the repo so I can turn on the common example tests instead of the examples compilation test that was added to this repo to be able to verify examples (the common test version is more enhanced at this point).

Since these are considered obsolete, maybe we should push a comment block to them saying so. Keeping this issue open so we can do this change to the examples files before next release.
